{% set data = load_setup_py_data() %}

package:
    name: era5grib
    version: {{ data.get('version') }}

source:
    path: .


build:
    script: "{{ PYTHON }} -m pip install . --no-deps"
    noarch: python
    number: {{ GIT_DESCRIBE_NUMBER }}


requirements:
    host:
        - python
        - pip
    run:
        - python
        - pandas
        - xarray
        - climtas
        - mule
        - f90nml
        - cdo
        - intake
        - xesmf

test:
    requires:
        - pytest
    imports:
        - era5grib
    files:
        - test
    commands:
        - py.test
